### ISSUE TITLE
Pipelinewise using non-existing fastsync

### ISSUE THREAD

**Issue by novotl** [transferwise/pipelinewise#578] opened 2020-11-26 22:50 UTC
**Describe the bug**
Running MongoDB tap with Redshift target for the first time tries to use FastSync but none exists. I believe the filters here https://github.com/transferwise/pipelinewise/blob/5b8e9fa80f620179a21777ea427114f0ace4be48/pipelinewise/cli/pipelinewise.py#L979-L980 are too broad, as some combinations (e.g. MongoDB -> Redshift) don't have FastSync support.

**To Reproduce**
1. Configurate mongo tap and redshift target (very basic configuration, basically only changed credentials)
2. `pipelinewise import --dir /cfg`
3. `pipelinewise run_tap --tap mongodb --target redshift`
```
Error(s) found:

Full log: /root/.pipelinewise/redshift/mongodb/log/redshift-mongodb-20201126_224523.fastsync.log.failed
Traceback (most recent call last):
  File "/pipelinewise/pipelinewise/cli/pipelinewise.py", line 1014, in run_tap
    transform=transform_params)
  File "/pipelinewise/pipelinewise/cli/pipelinewise.py", line 909, in run_tap_fastsync
    commands.run_command(command, self.tap_run_log_file)
  File "/pipelinewise/pipelinewise/cli/commands.py", line 361, in run_command
    raise RunCommandException(f'Command failed. Return code: {proc_rc}\n'
pipelinewise.cli.commands.RunCommandException: Command failed. Return code: 127
Error(s) found:
```
5. `cat /root/.pipelinewise/redshift/mongodb/log/redshift-mongodb-20201126_224523.fastsync.log.failed`
```
/bin/bash: /pipelinewise/.virtualenvs/pipelinewise/bin/mongodb-to-redshift: No such file or directory

-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:00:00.006800
-------------------------------------------------------
```

**Expected behavior**
FastSync mode should not be applied if the implementation does not exist. Singer should be used in this case.
 
**Your environment**
 - Version of PipelineWise: current master https://github.com/transferwise/pipelinewise/commit/5b8e9fa80f620179a21777ea427114f0ace4be48
 - Source type: MongoDB, both `FULL_TABLE` and `LOG_BASED` replication methods
 - Target type: Redshift

**Comment by Samira-El** [comment] 2020-11-27 11:06
Hey, thanks for raising this issue!

Indeed, we don't have FastSync for MongoDB - Redshift, that's because we don't use Redshift at TransferWise and didn't want to spend time on it.

I saw your PR, wdyt about adding the pair MongoDB - Redshift to FastSync, redshift is already implemented, so all we need is a script that glues mongoDB to redshift the same way as with Snowflake & PG?

I don't fully recommend relying on tap-mongodb to do the initial sync, it's not designed to do that if you set your replication method to `LOG_BASED`.

**Comment by novotl** [comment] 2020-11-27 14:40
As I'm diving deeper into syncing MongoDB to Redshift, I don't think implementing the FastSync is that simple to achieve what I want.

I would like to use the `data_flattening_max_level` [property ](https://github.com/transferwise/pipelinewise-target-redshift/blob/7e9e9e114452d2b33e02a0a911ee961c49f5ec5a/target_redshift/db_sync.py#L318) of the Redshift target to flatten the Mongo object into several columns. That is however not possible, because the MongoDB tap produces [very simple schema ](https://github.com/transferwise/pipelinewise-tap-mongodb/blob/9bf7c6546007cea8ae969159a2b6c29e18f2bff6/tap_mongodb/db_utils.py#L195-L202) that doesn't contain any nested fields. Although the Redshift tap will flatten records just fine, it will [throw them out](https://github.com/transferwise/pipelinewise-target-redshift/blob/7e9e9e114452d2b33e02a0a911ee961c49f5ec5a/target_redshift/db_sync.py#L374) because of the initial schema. I think it should be possible to discover the Mongo schema the same way as [valid-replication-keys are done](https://github.com/transferwise/pipelinewise-tap-mongodb/blob/9bf7c6546007cea8ae969159a2b6c29e18f2bff6/tap_mongodb/db_utils.py#L169-L182).

I don't see any similar flattening support in the Mongo or Redshift FastSync implementations. I also though about using [JSONPath option](https://docs.aws.amazon.com/redshift/latest/dg/copy-usage_notes-copy-from-json.html#copy-usage-json-options) for Redshift copy but that is a dead end since the Redshift target uses `csv` format.

I also tried MongoDB -> PG, but it just dumps all the records into one JSON column, which is not very useful in a database like PG.

**Comment by koszti** [comment] 2020-11-30 16:44
@novotl you're right, `data_flattening` option is not available in fastsync because we had some not great real life experience with data flattening. The main problem with data flattening that it's easily producing very wide tables from nested JSONs especially when the JSON structure is changing rapidly. In this case you'll easily end up with tables with hundreds of columns where most of them filled with NULLs.

This behaviour makes data flattening option sounds nice but at the same time the output data is hard to use. Due to this reason the data flattening option is turned off by default.

> Although the Redshift tap will flatten records just fine, it will throw them out because of the initial schema.

Different schemas should not be a problem and PPW will alter the table after the fastsync. Fastsync will create a simple table structure with all the historical documents. If you want, you can enable `data_flattening` option and target-redshift will alter the table and will flatten the newly received records.

> I also tried MongoDB -> PG, but it just dumps all the records into one JSON column

Yes, this is the expected behaviour due to the unpractical user experience with flattened data detailed above. What we can recommend to post processing the PPW tables or use database specific JSON queries when using data:

* **Postgres** has extensive [JSON parsing functions](https://www.postgresql.org/docs/9.5/functions-json.html), so you can query data with standard SQLs, directly from JSON. Query performance is worse than indexed tables but you can transform the JSON data to more efficient tables by post-processing the PPW tables with the same JSON SQLs.
* **Snowflake** has the [VARIANT](https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html) column type and can run [SQL on semistructured data](https://docs.snowflake.com/en/user-guide/querying-semistructured.html). Performance remains fine because data in `VARIANT` columns transformed  internally in an efficient compressed columnar binary representation of the documents.
* **Redshift** unfortunately has limited JSON capabilities, but you still can try to use [JSON_EXTRACT_PATH_TEXT](https://docs.aws.amazon.com/redshift/latest/dg/JSON_EXTRACT_PATH_TEXT.html) functions to post-process the PPW tables into more consumable tabular format.

**Comment by novotl** [comment] 2020-12-01 10:07
Thank you for the explanation @koszti. Correct me if I'm wrong but are you suggesting this process to have entire table synced and in tabular format and continuously syncing new rows?
1. initial sync by FastSync (there is no data flattening)
1. flatten the table (from step 1) in a process outside of PPW
1. continue on syncing new rows with non-FastSync method that supports data flattening on the fly

To me, it seems that the step 2 is critical, and the flattening process should output exactly the same table schema as is the schema from step 3. Let me demonstrate with an example:
1. The source has these rows at the time of FastSync
```
{'document': {'a': 'a1', 'b': 'b1'}}
{'document': {'a': 'a2', 'b': 'b2'}}
```
2. FastSync produces this table (not flattened)
```
| document               |
| {'a': 'a1', 'b': 'b1'} |
| {'a': 'a2', 'b': 'b2'} |
```
3. New rows are added to the source (we're not changing the schema)
```
{'document': {'a': 'a3', 'b': 'b3'}}
{'document': {'a': 'a4', 'b': 'b4'}}
```
4. Now we don't run FastSync, but regular Singer.io, this supports data flattening that results in a table like
```
| document__a | document__b |
| a3          | b3          |
| a4          | b4          |
```
5. Now we should merge tables from step 2 and step 4. That should be trivial if there is an outside process that flattens the table in-place such that it has columns `document__a`, `document__b` between steps 2 and 3.
6. In the end I would like to have a table that looks like this
```
| document__a | document__b |
| a1          | b1          |
| a2          | b2          |
| a3          | b3          |
| a4          | b4          |
```
---
> Different schemas should not be a problem and PPW will alter the table whenever it's required after the fastsync finished. If you want, you can enable data_flattening option and target-redshift will alter the table and will flatten the newly received records.

From my testing, this is unfortunately not true in the case of MongoDB tap. That is because when Redshift target is flattening the records, it ignores all the flattened fields that are not in the flattened schema ([source](https://github.com/transferwise/pipelinewise-target-redshift/blob/7e9e9e114452d2b33e02a0a911ee961c49f5ec5a/target_redshift/db_sync.py#L371-L375)). MongoDB tap produces a **static** schema ([source](https://github.com/transferwise/pipelinewise-tap-mongodb/blob/9bf7c6546007cea8ae969159a2b6c29e18f2bff6/tap_mongodb/db_utils.py#L195-L202)). So following schema from the above example:
```
flatten_schema = ['document'] # this is static for MongoDB
flatten_record_fields = ['document__a', 'document__b']

# because none of the flatten_record_fields are in flatten_schema, the record_to_csv_line is
{'document': ''}

# but I would expect 
{'document__a': 'a1' , 'document__b': 'b1'}
```

**Comment by Samira-El** [comment] 2021-09-14 07:11
Fixed with PR: https://github.com/transferwise/pipelinewise/pull/787

**Closed by Samira-El** 2021-09-14 07:11 UTC
Labels: bug
