### ISSUE TITLE
Partial sync fails to run on it's own

### ISSUE THREAD

**Issue by podviaznikov** [transferwise/pipelinewise#999] opened 2022-07-24 17:11 UTC
I think new partial sync feature fails to run without previously executing full sync. Code seems to be looking for the file and fails to read it.

**To Reproduce**
1. Run partial sync from PG to Snowflake on a new configuration.
2. See error where the job will fail with some file reading exception.

**Expected behavior**
It seems that it should be possible to run partial sync without any prior run of the full sync.

**Screenshots**

**Your environment**
 - Version of PipelineWise 0.48.1
 - Source type and setup
 - Target type and setup

**Additional context**

**Comment by Samira-El** [comment] 2022-07-25 12:29
This is not a bug, partial sync is for one-off data fixes to patch data between two values.
It expects that you should already have an existing pipeline for the data.

Closing as invalid.

**Closed by Samira-El** 2022-07-25 12:29 UTC
Labels: bug
