### ISSUE TITLE
PostGres timestamptz converts to Snowflake timestamp_ntz

### ISSUE THREAD

**Issue by cap-itadmin** [transferwise/pipelinewise#606] opened 2021-01-07 16:03 UTC
**Describe the bug**
I have a postgres tap to S3, with a Snowflake target.  The replication key is a timestamptz column.  In Snowflake, the column is created as timestamp_ntz (ie, no time zone).   "2021-01-06 **11:06:**30.261" is an example of a time stamp; but it is UTC in the source system (displaying local time zone), so in Snowflake should be 6AM ET - i.e.,   "2021-01-06 **6:06**:30.261"

**To Reproduce**
Create timestamp_ntz column in postgres.  
Run tap

**Expected behavior**
Snowflake column will be timestamp_ntz

**Screenshots**

**Your environment**
Please advise how to identify the version.  It's current - i.e., Docker package downloaded this week.

**Additional context**

**Comment by Samira-El** [comment] 2021-01-07 16:17
Hey,

I'm not sure I'm fully understanding the issue.

date/timestamp type columns in the source are maped to Snowflake's timestamp_ntz, that is by design, all dates are converted to UTC and follow the ISO 8601 format.

**Comment by Samira-El** [comment] 2021-01-21 12:56
Closing as PostGres timestamptz converts to Snowflake timestamp_ntz is not a bug

**Closed by Samira-El** 2021-01-21 12:56 UTC
