### ISSUE TITLE
BigQuery End to End Tests not running

### ISSUE THREAD

**Issue by judahrand** [transferwise/pipelinewise#863] opened 2022-01-12 10:39 UTC
**Describe the bug**
At the moment it seems that most or all BigQuery End to End tests are skipped. Is this intentional? Is it due to a lack of testing infrastructure? Can this be put in place if so?

**Expected behavior**
The BigQuery End to End tests should all run and pass.

**Comment by Samira-El** [comment] 2022-01-12 10:42
Hey, this is not a bug, there is no underlying bigquery instance to be used for e2e tests hence they're skipped.
If you use PipelineWise to load to Bigquery, you have to make sure to run e2e tests locally against a bq instance.

**Comment by judahrand** [comment] 2022-01-12 10:52
Would it not be possible to use BigQuery's Free Tier to conduct the end to end tests? Within this repo? 

https://cloud.google.com/bigquery/pricing#free-tier

**Comment by Samira-El** [comment] 2022-01-12 13:44
The free tier is nice! I reckon though that we are not interested in setting this up and running the tests for this component as this target was an external contribution and we don't use it at Wise.

**Comment by judahrand** [comment] 2022-01-14 10:39
I think there is an issue here 🤔 There is no way for the main project to ensure that it actually works. If the project is shipping a FastSync for a tap-target combination should this not be tested?

From my efforts so far trying to get the BigQuery e2e tests running - I'm not even sure they currently work / are correct. There seem to be obvious typos/bugs/failures.

**Comment by Samira-El** [comment] 2022-02-10 11:38
Closing this.

**Closed by Samira-El** 2022-02-10 11:38 UTC
Labels: question
